### ISSUE TITLE
Handle when perl*.pod files in pods dir not pod

### ISSUE THREAD

**Issue by kiwiroy** [perl-pod/pod-simple#108]
Because of the decisions that [installperl](https://github.com/Perl/perl5/blob/191f8909fa4eca1db16a91ada42dd4a065c04890/installperl#L533-L544) makes the `perl*.pod` files can reside in a `pods` directory rather than `pod`. The debugger handles this [thus](https://github.com/Perl/perl5/blob/bf3e41ff5d42bd65e92e06ce1b1b8f24064a178a/lib/perl5db.pl#L9036-L9038) looking for a `pods` dir first.

[`Pod::Simple::Search->find`](https://metacpan.org/pod/Pod::Simple::Search#$search->find(-$pod,-@search_dirs-)) is able to check the `pod` directory, but no checking is done on a `pods` directory.

> If any of the given search directories contains a pod/ subdirectory, then it is searched. (That's how we manage to find perlfunc, for example, which is usually in pod/perlfunc in most Perl dists.)

There are two blocks of code that appear affected:
* [`find`](https://github.com/perl-pod/pod-simple/blob/master/lib/Pod/Simple/Search.pm#L614-L619)
* [`_path2modname`](https://github.com/perl-pod/pod-simple/blob/master/lib/Pod/Simple/Search.pm#L262)

**Comment by khwilliamson** [comment]
Were you planning on issuing a pull request, given that you made a commit to your clone of this repository?

**Comment by kiwiroy** [comment]
Yes, now done.

**Comment by khwilliamson** [comment]
How soon do you need a new release?  I'm wondering if I should wait to see if other issues arise from the release earlier this week.

**Comment by kiwiroy** [comment]
It's not urgent.
