### ISSUE TITLE
Tab indentation converted to spaces

### ISSUE THREAD

**Issue by Grinnz** [perl-pod/pod-simple#110]
See https://github.com/metacpan/MetaCPAN-Pod-XHTML/issues/2. Tab indentation seems to be unconditionally converted to 8 spaces. This is a problem for certain Makefile example code that then doesn't work when directly copy-pasted, even if the extra indent for the verbatim block is removed. Perhaps there could be an option to preserve tabs, unless this causes issues elsewhere.

**Comment by khwilliamson** [comment]
Pod-Simple 3.40 now contains a new method, expand_verbatim_tabs(), which if called with 0 achieves the desired behavior in this issue
