### ISSUE TITLE
Weird interaction between encodings and nbsp_for_S

### ISSUE THREAD

**Issue by rra** [perl-pod/pod-simple#115]
This Perl program:

```
use Pod::Text;
my $pod = "=pod\n\nfoo S<  > bar";
my $out;
my $parser = Pod::Text->new;
$parser->output_string(\$out);
$parser->parse_string_document($pod);
print $out;
```

produces:

```
    foo    bar
```

as expected because `Pod::Text` sets `nbsp_for_S` to a true value. But with this slight modification:

```
use Encode qw(decode);
use Pod::Text;
my $pod = "=pod\n\nfoo S<  > bar";
my $out;
my $parser = Pod::Text->new;
$parser->output_string(\$out);
$parser->parse_string_document(decode("utf-8", $pod));
print $out;
```

it produces:

```
    foo bar
```

In other words, the non-breaking spaces have been turned into regular spaces and then collapsed by `Pod::Text`.

There's a bunch of post-processing in `Pod::Text` that made it hard to track this down, but I was able to determine that somehow the transformation done by `_change_S_to_nbsp` doesn't happen properly and by the time that the string is passed down to the `Pod::Text` callback for a para, these non-breaking spaces are just spaces.

Based on the above, this appears to be related to the Perl internal UTF8 flag on the input string, and I suspect is because the implementation of `_change_S_to_nbsp` tries to do a regex substitution of an invalid UTF-8 code point, although I wasn't able to reproduce the problem in a reduced test case.

I think this is behind some weird problems I've seen with `S<>` not working as expected with `Pod::Text`, although I'm not sure how to go about fixing it, or even if I've found the right problem.

**Comment by rra** [comment]
Never mind, the problem was entirely internal to `Pod::Text`. I just needed to take a walk to realize it. It was indeed due to the UTF8 flag, but it was changing the behavior of `\s` in a regex in `Pod::Text`, not anything inside `Pod::Simple`.

**Comment by karenetheridge** [comment]
> it was changing the behavior of \s in a regex in Pod::Text

what regex was that? How was the behaviour changed?

**Comment by rra** [comment]
The regex was:
```
s/\s+/ /g;
```
and that was matching non-breaking spaces inserted by `Pod::Simple` as well and collapsing them down to a regular space. I didn't realize that was running before the code I was looking at and getting rid of the non-breaking spaces.

**Comment by karenetheridge** [comment]
So not related to the utf8 flag then?

**Comment by rra** [comment]
It is, I think. Here's what I think happened.

Normally, for POD input that doesn't declare an encoding, `Pod::Simple` is careful to read that input without doing any encoding transformations, which means the input from the file ends up as raw strings. That's then parsed into treelets and so forth, all still as raw strings, and reaches `Pod::Text` that way. Because it's a raw string, `\s` then only matches the traditional ASCII whitespace characters, and the non-breaking space is treated as a non-space character.

I observed the altered behavior both when passing in a document as a string that had already been through `decode` and, critically, when processing POD files with `=encoding utf8`. The difference in both cases is that this means the input string or data goes ends up as a native string with the UTF8 flag set. `Pod::Simple` then parses that and so forth and that flag is preserved in all the subsequent strings until it gets passed down into `Pod::Text`, which does a regex match. Since the UTF8 flag is set on the string, `\s` then matches all Unicode whitespace, which includes the non-breaking space.

It all makes sense once I thought it through. It's just very subtle. I changed the regex to instead be:
```
s/[ \t\n]+/ /g
```
and everything works as expected now. That means that I won't collapse other types of Unicode spaces that might appear in the document, but I'm okay with that.

**Comment by rra** [comment]
Thinking this through some more, I suppose one could make an argument that, for consistency, `Pod::Simple` should always convert its input to UTF8-tagged strings even if it is pure ASCII, so that downstream behavior is consistent. It would be a backwards-incompatible change in some subtle ways, but it might make things better in the long run.

**Comment by khwilliamson** [comment]
On 12/26/19 11:32 AM, Russ Allbery wrote:
> It is, I think. Here's what I think happened.
> 
> Normally, for POD input that doesn't declare an encoding, |Pod::Simple| 
> is careful to read that input without doing any encoding 
> transformations, which means the input from the file ends up as raw 
> strings. That's then parsed into treelets and so forth, all still as raw 
> strings, and reaches |Pod::Text| that way. Because it's a raw string, 
> |\s| then only matches the traditional ASCII whitespace characters, and 
> the non-breaking space is treated as a non-space character.
> 
> I observed the altered behavior both when passing in a document as a 
> string that had already been through |decode| and, critically, when 
> processing POD files with |=encoding utf8|. The difference in both cases 
> is that this means the input string or data goes ends up as a native 
> string with the UTF8 flag set. |Pod::Simple| then parses that and so 
> forth and that flag is preserved in all the subsequent strings until it 
> gets passed down into |Pod::Text|, which does a regex match. Since the 
> UTF8 flag is set on the string, |\s| then matches all Unicode 
> whitespace, which includes the non-breaking space.
> 
> It all makes sense once I thought it through. It's just very subtle. I 
> changed the regex to instead be:
> 
> |s/[ \t\n]+/ /g |
> 
> and everything works as expected now. That means that I won't collapse 
> other types of Unicode spaces that might appear in the document, but I'm 
> okay with that.
> 

You could get closer to the previous behavior if you change that \n to 
\v.  It may not matter to your application, but that would match \r, \f, 
\cK also, plus some Unicode vertical spaces.

But actually, currently the only other space in Unicode that  I think 
could be problematic if you were to change it is U+202F NARROW NO-BREAK 
SPACE.
