### ISSUE TITLE
Archive contains swp file and .github dir

### ISSUE THREAD

**Issue by perlpunk** [perl-pod/pod-simple#123]
I noticed that when trying to update to 3.41 in the perl modules repo in openSUSE Open Build Service.
https://metacpan.org/source/KHW/Pod-Simple-3.41/.ChangeLog.swp
https://metacpan.org/source/KHW/Pod-Simple-3.41/.github
These should probably be excluded from the archive.

**Comment by khwilliamson** [comment]
I agree.  I'm hopeful we will be getting an enhancement soon that will cause a new version to be released, and these can be removed.  If you think a new release should be done just for the flaws you uncovered, let me know

**Comment by khwilliamson** [comment]
This should be fixed in 3.42, just released
