### ISSUE TITLE
Optionally Suppress Version Number Comments (Allow Deterministic Builds)

### ISSUE THREAD

**Issue by chromatic** [perl-pod/pod-simple#148]
I'm working on a system attempting to produce [reproducible builds](https://reproducible-builds.org/). When a Perl module uses a stack which includes `Pod::Simple` in the build process (such as using `Pod::Man` to generate man pages), the resulting output includes the version numbers of `Pod::Simple`.

For example, when building `Mojolicious`, the generated output for binaries such as `morbo` includes:

```
.\" Automatically generated by Pod::Man 4.14 (Pod::Simple 3.42)
.\"
.\" Standard preamble:
.\" ========================================================================
```

I'd like to be able to consolidate built modules when the output is bit-for-bit identical.

It's okay if `Pod::Simple` generates *different* output when the behavior of the module changes. However, if I had a way to suppress version number output in certain circumstances, I could re-use more built modules because there'd be fewer differences between them.

Ideally I could set an environment variable in my build system that would cover all of the cases where `Pod::Simple` may be invoked during a build process.

I'm happy to explain further or elaborate if my use case is still fuzzy.

**Comment by haarg** [comment]
This is done by Pod::Man, which is part of the podlators distribution, not Pod-Simple.

**Comment by haarg** [comment]
https://github.com/rra/podlators/blob/main/lib/Pod/Man.pm#L1117

**Comment by chromatic** [comment]
I was thinking of a way to suppress or simplify the output of the `version_report` method in `Pod::Simple`. If you think suppressing the output altogether in podlators is preferable, I'm happy to migrate this issue to that distribution.

**Comment by haarg** [comment]
It doesn't make much sense to me that a method named `version_report` would produce anything other than a version report.

None of the modules in this dist include the output from `version_report`. And even in podlators, it appears that only Pod::Man does. It may be reasonable to just remove it from there without an option.

**Comment by chromatic** [comment]
Thanks for the recommendation. I'll close this in favor of a similar query with podlators.

**Comment by rra** [comment]
For the record, the reason why Pod::Man does this is due to this statement in perlpodspec:

- When rendering Pod to a format that allows comments (i.e., to nearly any format other than plaintext), a Pod formatter must insert comment text identifying its name and version number, and the name and version numbers of any modules it might be using to process the Pod.

I'm therefore hesitant to change Pod::Man to stop doing this unless perlpodspec is changed. (The other modules in the podlators distribution fall under the "do not allow comments" exception.)

**Comment by haarg** [comment]
That seems like a pretty strange thing to have in the spec, and I would support removing it. Most other formatters don't follow that rule, including many that allow comments.

**Comment by rra** [comment]
Who owns perlpodspec these days? Is it maintained directly in the main Perl 5 repository? I can submit a PR.

**Comment by haarg** [comment]
Yes, perlpodspec is maintained in core.
