### ISSUE TITLE
Pod-Simple-3.45-TRIAL1: Warning: the following files are missing in your kit

### ISSUE THREAD

**Issue by twata1** [perl-pod/pod-simple#153]
Hello,

Running Strawberry Perl 5.26.1 64 bit, I noticed the following message.

```
C:\home\bathtub1>cpan KHW/Pod-Simple-3.45-TRIAL1.tar.gz

(snip)

Checking if your kit is complete...
Warning: the following files are missing in your kit:
        t/20_skip.t
Please inform the author.
Generating a gmake-style Makefile
Writing Makefile for Pod::Simple
Writing MYMETA.yml and MYMETA.json
(C:\Strawberry\perl\bin\perl.exe Makefile.PL exited with 0)

(snip)

```

Thank you,

**Comment by khwilliamson** [comment]
Thank you for reporting this.

Please try this again with TRIAL2, just now uploaded

**Comment by twata1** [comment]
I have tried TRIAL2 in several Perl versions.
This issue itself appears to have been fixed. (Although it seemed like t/search50.t was taking a long time to run.)

Anyway, thank you for your response!
