### ISSUE TITLE
Pod::Simple t/JustPod_corpus.t  fails its test suite if it is run from a directory with "temp" in its name

### ISSUE THREAD

**Issue by Corion** [perl-pod/pod-simple#159]
This happened when cutting the 5.39.7 Perl developer release. Perl was unpacked into a directory `/tmp/perltemp/` and the check in `JustPod_corpus.t` failed:

```
sub wanted {
    push @test_files, $File::Find::name
      if $File::Find::name =~ /\.pod$/
      && $File::Find::name !~ /temp/; # ignore any files named temp,
                                      # a different test file may have
                                      # created it
  }
```

A fix would likely to be to check the basename of `$File::Find::name` for `temp` instead of checking the complete filename.

**Comment by jkeenan** [comment]
Given https://github.com/perl-pod/pod-simple/pull/160/commits/a198393a7d1c8fe3f73299b1a81fcbbab30575e9, this ticket appears to be Closable.
