### ISSUE TITLE
Wrapping POD at certain column?

### ISSUE THREAD

**Issue by kberov** [perl-pod/pod-simple#66]
HI,
I was looking for a simple filter to wrap my POD documentation at certain column in order
to keep it pretty even when reading it in my text editor. I think this would be a much used feature by CPAN authors.
I saw there is already Pod::Simple::Text which does some wrapping, but could not find how to just re-flowing/re-wrapping the POD and output again POD. Is there something which can logically reside
in the Pod::Simple::Wrap namespace? something like Pod::Wrap but using Pod::Simple.  I am keen on Implementing this in this project if it does not yet exist in some form. I may need just some guiding points. 

Thanks!

**Comment by theory** [comment]
Does not exist that I know of; I just let Emacs wrap my Pod. But I have no objection to Pod::Wrap.
