### ISSUE TITLE
August PR Challenge

### ISSUE THREAD

**Issue by lejeunerenard** [perl-pod/pod-simple#68]
Hey all,

I was assigned Pod::Simple as my August module for the [PR Challenge](http://cpan-prc.org). Originally I was assigned @theory's fork of this repo, but i'm assuming this is actually repo I should fork and PR onto.

I was wondering if you had anything that jumps to mind as a project for my PR. If not, I'll do some poking around to see what TODOs, bugs or ideas I can find.

**Comment by theory** [comment]
This is the correct repo. However, I suggest posting to [pod-people](http://lists.perl.org/list/pod-people.html) rather than opening an issue for this.
