### ISSUE TITLE
There is no simple way to get POD errors

### ISSUE THREAD

**Issue by van-de-bugger** [perl-pod/pod-simple#71]
Copied from CPAN RT [#105220](https://rt.cpan.org/Ticket/Display.html?id=105220):

If parser finds any errors in POD, it either send them to `stderr`, or creates a special section at the end. Caller does not have a simple way to get error messages. I am working on a plugin for a third-party system. Plugin should report any errors via `$logger->log( $message )`, so neither `stderr` nor added section is convenient to me. I would like to have some method to get parsing errors, for example:

    $parser->no_errata_section( 0 );
    $parser->complain_stderr( 0 );
    $parser->parse_...( ... );
    if ( $parser->any_errata_seen() ) {
        $logger->log( $parser->errata_seen() );
    }

**Comment by van-de-bugger** [comment]
Note that I am not the only person who faced this issue. Look at Test::Pod::No404s module by Apocalypse, line ~69:

    # is POD well-formed?
    if ( $parser->any_errata_seen ) { 
        ... 
        # TODO ugly, but there is no other way to get at it?
        foreach my $l ( keys %{ $parser->{errata} } ) {
            $Test->diag( " * errors seen in line $l:" );
            $Test->diag( " * $_" ) for @{ $parser->{errata}{$l} };
         }
    }

**Comment by marcgreen** [comment]
Fixed in v3.32
