### ISSUE TITLE
Shall I issue a pull request for a patch that sends debug to STDERR?

### ISSUE THREAD

**Issue by khwilliamson** [perl-pod/pod-simple#75]
It consists of 355 changes in this form:
 -  DEBUG > 4 and print "MANY_LINES is ", MANY_LINES(), "\n";
 +  DEBUG > 4 and print STDERR "MANY_LINES is ", MANY_LINES(), "\n";
I wrote it because I was trying to get debug from a smoker machine whose only access I had was to receive smoke reports.  The STDOUT of tests is absorbed by, I think it's harness, so I had to add these to see what was going on.

**Comment by theory** [comment]
Uh, sure. We'll want to smoke it pretty hard, though.
