### ISSUE TITLE
META: recommend Encode 2.78 for runtime

### ISSUE THREAD

**Issue by dolmen** [perl-pod/pod-simple#77]
In Encode 2.78 the code page 1252 (the new default for Pod::Simple) is now pre-compiled (see dankogai/p5-encode#42), which means a speed improvement.

It would be helpful to advertise this to CPAN installers by marking Encode 2.78 as a `runtime`/`recommends` dependency in META.yml/META.json.

**Comment by khwilliamson** [comment]
Pod::Simple 3.35 is now available, and I believe it fixes this issue.  If I don't hear back from you that it is still a problem by January 1, 2017, I will close this ticket as fixed.

**Comment by dolmen** [comment]
Fix confirmed: https://metacpan.org/source/KHW/Pod-Simple-3.35/META.json#L33
