### ISSUE TITLE
Pod::Simple: events delivered in wrong order.

### ISSUE THREAD

**Issue by van-de-bugger** [perl-pod/pod-simple#79]
Hi,

Please consider trivial POD:

```
=head1 DESCRIPTION

    Verbatim paragraph.

=cut
```

For such a text, `Pod::Simple` 3.32 delivers following events:

```
<Document start_line="1">
  <head1 start_line="1">
    DESCRIPTION
  </head1>
  <cut start_line="5"/>
  <VerbatimFormatted start_line="3" xml:space="preserve">
        Verbatim paragraph.
  </VerbatimFormatted>
</Document>
```

Everything is correct, but order is wrong: `cut` event is delivered before than 3 events of verbatim paragraph.

Note: if paragraph is not verbatim, events are delivered in correct order.

[Test case](https://gist.github.com/van-de-bugger/e167bf55e2fec42bffbd).

**Comment by khwilliamson** [comment]
Thanks for the report.

This should now be fixed in version 3.36 now available from CPAN
