### ISSUE TITLE
Pod-Simple/t/encod04.t: send TODO diag to STDOUT

### ISSUE THREAD

**Issue by iabyn** [perl-pod/pod-simple#80]
See attached patch
[0001-Pod-Simple-t-encod04.t-send-TODO-diag-to-STDOUT.patch.txt](https://github.com/perl-pod/pod-simple/files/42914/0001-Pod-Simple-t-encod04.t-send-TODO-diag-to-STDOUT.patch.txt)

**Comment by karenetheridge** [comment]
aiee, we're still using Test.pm? I believe there was a plan to try to get that phased out in blead.

Note for the future: I've been using this patch when it's important to get diag output to STDERR:

```
# diag uses todo_output if in_todo :/
no warnings 'redefine';
*::diag = sub {
    local $Test::Builder::Level = $Test::Builder::Level + 1;
    my $tb = Test::Builder->new;
    $tb->_print_comment($tb->failure_output, @_);
};
```

**Comment by mvgrimes** [comment]
Is there value in converting to Test::More? I might be able to tackle that as my January PR Challenge.

**Comment by theory** [comment]
Some of the tests already use Test::More, so yeah, I would think it would be useful.

**Comment by khwilliamson** [comment]
Now merged
