### ISSUE TITLE
META.json Is Incomplete

### ISSUE THREAD

**Issue by theory** [perl-pod/pod-simple#84]
The last couple of releases of Pod-Simple, the `META.json` file has been incomplete. Compare the [3.32 `META.json`](http://search.cpan.org/src/MARCGREEN/Pod-Simple-3.32/META.json) to the [3.30 `META.json`](http://cpansearch.perl.org/src/DWHEELER/Pod-Simple-3.30/META.json). Notably, the dependencies are missing. This is bad for install toolchains that rely on the the MetaCPAN API to determine dependencies. I think we need a new release that fixes this issue stat.

**Comment by theory** [comment]
When creating a release, make sure you're using the latest version of ExtUtils::MakeMaker and its dependencies. Using the one that ships with Perl 5.22 should be sufficient. Then `make dist` will create the appropriate files.

**Comment by karenetheridge** [comment]
Also ensure that CPAN::Meta is up to date.

**Comment by khwilliamson** [comment]
This was fixed by 3.35
