### ISSUE TITLE
Can't locate object method "parse_characters"

### ISSUE THREAD

**Issue by mjegh** [perl-pod/pod-simple#91]
Can't locate object method "parse_characters" via package "Pod::Simple::HTML" at /home/perlbrew/perl5/perlbrew/perls/perl-5.24.2/lib/site_perl/5.24.2/Pod/Simple/BlackBox.pm line 394.

As far as I can see there is no method parse_characters in Pod::Simple anywhere. There is a hash key parse_characters though.

This problem seems to happen on just about all my modules.

**Comment by khwilliamson** [comment]
Could you furnish some text where it is failing please?  That would help us debug it.

**Comment by khwilliamson** [comment]
That method is created by using a glob, so it does exist, and is used internally.  We just need an example where its not working to see what's going wrong in your particular case.

**Comment by mjegh** [comment]
@khwilliamson I reported this over 8 months ago but I believe we still get the issue so I'll try and dig out some text.

**Comment by khwilliamson** [comment]
@megh, have you not found examples of this, or not had a chance to look.  If you can get me a failing case quickly, I can get it fixed in the next release

**Comment by mjegh** [comment]
oops, forgot again. I'll look it up now.

**Comment by mjegh** [comment]
ok. I can reproduce the issue again but when I tried to pare it down I failed until I realised we had our own Pod::Simple with a change in it (for another problem we found and fixed). It was version 3.20 and that isn't on metacpan so I'll have to find it on backpan to remind myself what we changed/fixed and then I can check the latest Pod::Simple out. I'll do that now.

**Comment by mjegh** [comment]
I'll close this now. The latest version works as we wanted once index is set to true which the pod says is the default but it didn't create an index without setting it.
