### ISSUE TITLE
=encoding utf8 not supported by rtf encoder

### ISSUE THREAD

**Issue by japharl** [perl-pod/pod-simple#92]
If pod string is a utf8 string, and =encoding utf8 is specified at the beginning of the rtf output, utf8 is not written to the rtf file.

**Comment by japharl** [comment]
Note - tentative solution for myself was to use the perl module MsOffice::Word::HTML::Writer as a replacement for Pod::Simple::rtf .  The code change was reasonably straight forward for my purposes...

**Comment by khwilliamson** [comment]
Thanks for the report.  This will be fixed in the next release, in a couple weeks

**Comment by khwilliamson** [comment]
Thanks for the report.  This is  fixed in version 3.36 now available on CPAN

**Comment by japharl** [comment]
++ Thanks.
