### ISSUE TITLE
POD commands in literal strings shall be skipped

### ISSUE THREAD

**Issue by stphnlyd** [perl-pod/pod-simple#95]
Now it checks POD commands in literal strings and can have false report. Below is an example. 

```perl
use 5.014;
use warnings;
use Pod::Simple;

my $checker = Pod::Simple->new;
$checker->complain_stderr(1);
$checker->parse_string_document( <<'EOT' );

my $pod_snippet = <<'POD';

This is a snippet that can be embedded into other POD docs.

=item * Foo

=item * Bar

POD

EOT

say "errata seen: ", $checker->any_errata_seen; 
```
It gives below error. And it can cause Test::Pod test to fail. 
```
Pod input around line 6: '=item' outside of any '=over'
Pod input around line 6: =over without closing =back
errata seen: 2
```

If you're curious why I have such kind of code, it's because I would like to have this kind of POD snippet which can be processed to be embedded into other POD docs. Things like Pod::Weaver::Plugin::Include does not meet my need.

**Comment by karenetheridge** [comment]
In the example you provided, you don't do anything with `$pod_snippet`.

**Comment by karenetheridge** [comment]
(erroneous comment deleted)

**Comment by karenetheridge** [comment]
I don't think you are using the api correctly. The snippet you provided *isn't* a valid pod document on its own, so it's not valid to try to parse it as such.  You should instead parse it as paragraph(s), which can be embedded.

**Comment by stphnlyd** [comment]
@karenetheridge I am not trying to parse it, it's just that I get Test::Pod failure on this code. My point is that ideally the pod parser should ignore it rather than trying to parse it.

**Comment by khwilliamson** [comment]
I think this is asking too much of this module.  To know this was in a heredoc would require the module to know how to parse Perl code in general.  I think we can document this as a deficiency and recommend that if you do have pod in a heredoc, that you use the more modern indented heredocs instead.

**Comment by stphnlyd** [comment]
@khwilliamson I agree.

**Comment by khwilliamson** [comment]
I was looking around as to where to add such documentation.  The only obvious place to me was perlpodspec.  If you someone has ideas, or hopefully a pull request, let me know.

**Comment by stphnlyd** [comment]
@khwilliamson IMO it's best to be in Pod::Simple. After all, it's a limitation of Pod::Simple instead of the POD spec. I would avoid doing the PR myself as I am not a native English speaker...

**Comment by toddr** [comment]
I'm not certain but I think I just reported the same bug here: https://rt.cpan.org/Ticket/Display.html?id=129722

I want to determine if a perl script has POD by doing:
```perl -MPod::Simple -E'my $p = Pod::Simple->new; $p->parse_file("test.pl"); say $p->content_seen'```

But it chokes on the below code.

```perl
#!perl

use strict;
use warnings;

my $key = q{-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.14 (GNU/Linux)

mQENBFG2P7gBCAD2fN0JcFLjYmWZuFL/8wJvOL1jX+4eWKd59ej07E8WIGoechzB
uOTq2uZsaoclOOb0IpVkkd9klm/uu03BNclPjZRqFr/iCQO2Jjw0C+FPuZRGky9e
5alKLfLutYwv/rUTou4V7ffDGsAOU3yA3f+Ydtq685Thy9qr9TU078K3nMjcPvhI
X0kqyvnoJ8bLWqANxg3ST0PYREInJGmbmU0CBE3rQ5tUbWj+pizZVRzWWVemyWW7
yFNwtQbxhyTb5wDvqMkgENZJok+Kx+6bC5/lg5Hm4hUlVDZyuP213DU280kx5NqA
vY+Pq2/7grZoBmljD+wRjSFK2MI4gWkb2+ftABEBAAG0NmNQYW5lbCBEZXZlbG9w
bWVudCBCdWlsZCBLZXkgPHJlbGVhc2UtdGVhbUBjcGFuZWwubmV0PokBOAQTAQIA
IgUCUbY/uAIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQDXk2bKkg6YAD
PAgAmXeGA8ZphsJIEH+5dme96aHKd014Yk1M4yLa36Ij9XWBAemEsFtsOhE1aH91
vWIAvo9xwAzuw7hLK25P3o3I7n54nL4wYtj6kR0LQrnsyrh2e7ZQ82TBYpW2BUYD
v7YxKCEA0i9gcmBSxrqyp3k66TCuawDvGvoLWhET+RWjILzvGnovylLuZ+rp7oOj
BLVatMhjgGdjtsIVlG1fd42Zm1bWluhMq+bZLwc7LgPMvZKP8EehrM/8qWkIMy08
U2emAtAOunf+zK6VHro25THGtujdKTSyR7+Hb6Iwnune1r1yBZRYiI+Nyyj9ZTMD
nnHp/18q8p+w53aOwp23mF5QybkBDQRRtj+4AQgAtj35TX0kgwBmIb9MCew3M3Vi
FNJ+g9ErzFnVi3l5H1owTN3eohz0MX71qNt/mrnM0oTm/SM9fx1xERAxQJWLM4oL
RYCKVja9oW8WpRg5YaRMVu69GFyU2U8Dr2SVQBxX58SMoLJW0UgsE2tsR2Q861vH
a+P9Q7fgNBc5aWJv+PrWtaTJHotWB77pqkt/B59S+OcX0IDcx22o3qHUDmAyffF7
Qa0JHH0rrVaBa5PpaTae/OztprL+dNBbumHMTypqrMOUhcQFIEaww+UTUbodothp
Rf+y56hQ2uTQ/AN+zEioJHleBeW0ATqqdS1HSmHLM8CeiIvYfTEio//VFYE91QAR
AQABiQEfBBgBAgAJBQJRtj+4AhsMAAoJEA15NmypIOmAm4gIAJydiXeHOdw6uGI3
t918H1PYvDiHdl6RVLzM4AM/SULhJfbFcFTudT4hTXjKD9gbf9AZg+yrih/qMBwz
DhRS1i/znXF3rdnBDP2pJBtM4JLaM4tZPqId6/l86Ix7nM+Vyb69vg5NUggKMsW9
jWnUBO9RUwb9BqfBPiomxFpWYefWfAqNILzBeKBBR+YrY7xbXUKPcj9VJYZl9fWl
dm+aSxLl7V3VUJFIe6CFDU13zhZ3yvjIuVkp6l//ZHcDcX014vnnh3FoElI92kFB
JGFU23Vga5Tfz0Epybwio9dq1gzrZ/PIcil2MnEcUWSrIStriv4hAbf0MXcNRHOM
oOV7xKU=
=y6KV
-----END PGP PUBLIC KEY BLOCK-----};

print $key;
exit;
```

**Comment by khwilliamson** [comment]
It turns out that the module is way too lenient in what it thinks is pod, so the =y6KV ine in the public key was triggering it to consider it to be pod.  The fix is to see pod only when one of the very few actual pod commands is found, not just something that syntactically could be a pod command.  The list of such commands is very stable.  The next release will have this fixed.

This does not solve the original problem reported in this issue, in which there were legal pod commands but were in a quoted string, so shouldn't count.

**Comment by khwilliamson** [comment]
Actually that approach didn't work, as Pod::Simple is extensible.  But another approach worked, and the pgp key no longer is considered content, and the pod has changed to indicate that equal signs in column 1 of literal strings can be considered to be pod
